variables:
  GIT_STRATEGY: clone

.only-default: &only-default
  only:
    - merge_requests
    - master

.print-system-info: &print-system-info
  - lsb_release -a
  - pwd
  - python3 --version
  - which python3

.activate-venv: &activate-venv
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 -m pip install --upgrade pip
  - which python3

before_script:
  - *print-system-info
  - *activate-venv
  - python3 -m pip install .

test sphinx documentation:
  <<: *only-default
  before_script:
    - *print-system-info
    - *activate-venv
    - python3 -m pip install .[doc]
  script:
    - cd docs
    - make html

pytest:
  <<: *only-default
  before_script:
    - *print-system-info
    - *activate-venv
    - python3 -m pip install .[test]
  script:
    - python3 -m pytest --durations=0 --cov-config=.coveragerc --cov=./
