variables:
  GIT_STRATEGY: clone

pytest:
  script:
    - python3 -m pip install pytest pytest-cov
    - python3 -m pip install -r requirements.txt
    - python3 -m pytest --durations=0 --cov-config=.coveragerc --cov=./
