variables:
  GIT_STRATEGY: clone

.only-default: &only-default
  only:
    - merge_requests
    - master

.print-system-info: &print-system-info
  - lsb_release -a
  - pwd
  - python3 --version
  - which python3

.activate-venv: &activate-venv
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 -m pip install --upgrade pip
  - python3 -m pip install wheel
  - which python3

before_script:
  - *print-system-info
  - *activate-venv
  - python3 -m pip install .

Documentation:
  <<: *only-default
  before_script:
    - *print-system-info
    - *activate-venv
    - python3 -m pip install .[doc]
  script:
    - cd docs
    - EXECUTE_NB= make html

Tests:
  <<: *only-default
  before_script:
    - *print-system-info
    - *activate-venv
    - python3 -m pip install .[test]
  script:
    - python3 -m pytest --cov=boostcfg --cov=pawian

Style:
  <<: *only-default
  before_script:
    - *print-system-info
    - *activate-venv
    - python3 -m pip install .[dev]
  script:
    - cspell $(git ls-files)
    - markdownlint $(git ls-files | grep --regexp="^.*.md$")
    - pre-commit run -a
