variables:
  GIT_STRATEGY: clone

.only-default: &only-default
  only:
    - merge_requests
    - master

before_script:
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 -m pip install virtualenvwrapper
  - source venv/bin/virtualenvwrapper.sh
  - add2virtualenv $(pwd)
  - python3 -m pip install -r requirements.txt

test sphinx documentation:
  <<: *only-default
  script:
    - which python3
    - python3 -m pip install -r docs/requirements.txt
    - cd docs
    - make html

pytest:
  <<: *only-default
  script:
    - python3 -m pip install pytest pytest-cov
    - python3 -m pip install -r requirements.txt
    - python3 -m pytest --durations=0 --cov-config=.coveragerc --cov=./
