name: pre-commit

on:
  push:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - main
      - epic/*
      - "[0-9]+.[0-9]+.x"
  workflow_dispatch:

jobs:
  style:
    name: Style checks
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        # cspell:ignore precommit
        run: |
          python -m pip install --upgrade pip
          pip install -e .[precommit]
      - name: Run non-local pre-commit hooks
        run: |
          pre-commit run flake8 -a --color always
          pre-commit run mypy -a --color always
          pre-commit run pylint -a --color always
