name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build documentation and push to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[doc]
          sudo apt-get -y install pandoc
      - name: Build documentation and run notebooks
        working-directory: docs
        env:
          EXECUTE_NB: YES
        run: make html
      - name: Move documentation build files to main directory
        run: |
          find . ! -regex '^./docs/_build/html\(/.*\)?' ! -regex '^./.git\(/.*\)?' -delete | true
          mv docs/_build/html/* docs/_build/html/.[^.]* .
          rm -rf docs
      - name: Commit to gh-pages orphan branch
        run: |
          git checkout --orphan gh-pages
          git add -A
          git config --global user.name "GitHub"
          git config --global user.email "noreply@github.com"
          git status -s
          git commit -m "Upload documentation build files"
      - name: Force-push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push origin gh-pages --force
