name: GitHub Pages
env:
  PYTHONHASHSEED: "0"

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build documentation and push to GitHub Pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: |
            ${{ github.workflow }}-${{ github.job }}-${{ runner.os }}-${{ hashFiles('.constraints/py3.*.txt', 'setup.cfg', 'src/**') }}
          path: |
            ./docs/_build
            ~/.cache/pip/
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -c .constraints/py3.8.txt .[doc] tox
          sudo apt-get -y install pandoc
      - name: Build documentation and run notebooks
        run: tox -e docnb
      - name: Move documentation build files to main directory
        run: |
          find . ! -regex '^./docs/_build/html\(/.*\)?' ! -regex '^./.git\(/.*\)?' -delete | true
          mv docs/_build/html/* docs/_build/html/.[^.]* .
          rm -rf docs
      - name: Commit to gh-pages orphan branch
        run: |
          git checkout --orphan gh-pages
          git add -A
          git config --global user.name "GitHub"
          git config --global user.email "noreply@github.com"
          git status -s
          git commit -m "Upload documentation build files"
      - name: Force-push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}
          git push origin gh-pages --force
